import React, { useEffect, useState } from 'react';
import { AlertCircle, CheckCircle2, Eye, HeartHandshake, Plus, RefreshCw, X } from 'lucide-react';
import { db } from '../lib/db';
import '../styles/admin-donations.css';

const INITIAL = { hospitalId:'', category:'blood', title:'', description:'', patientSummary:'', urgency:'normal', bloodGroup:'A+', unitsNeeded:'1', amountTarget:'', location:'', contactInstructions:'', expiresAt:'' };
const GROUPS = ['A+','A-','B+','B-','AB+','AB-','O+','O-'];

export default function AdminDonationRequests({ staffId }) {
  const [requests,setRequests]=useState([]), [hospitals,setHospitals]=useState([]), [form,setForm]=useState(INITIAL);
  const [showForm,setShowForm]=useState(false), [selected,setSelected]=useState(null), [responses,setResponses]=useState([]);
  const [loading,setLoading]=useState(true), [saving,setSaving]=useState(false), [error,setError]=useState('');
  const load=async()=>{setLoading(true);setError('');const [{data:r,error:re},{data:h,error:he}]=await Promise.all([db.donations.getAllRequests(),db.hospitals.getAll()]);setRequests(r||[]);setHospitals(h||[]);setForm(current=>({...current,hospitalId:current.hospitalId||h?.[0]?.id||''}));if(re||he)setError((re||he).message);setLoading(false)};
  useEffect(()=>{load()},[]); // eslint-disable-line react-hooks/exhaustive-deps
  const create=async e=>{e.preventDefault();setSaving(true);setError('');const {error:createError}=await db.donations.createRequest({...form,staffId,expiresAt:form.expiresAt?new Date(form.expiresAt).toISOString():null});setSaving(false);if(createError){setError(createError.message);return}setShowForm(false);setForm({...INITIAL,hospitalId:hospitals[0]?.id||''});await load()};
  const changeStatus=async(id,status)=>{const {error:updateError}=await db.donations.updateRequest(id,{status});if(updateError){setError(updateError.message);return}await load()};
  const viewResponses=async request=>{setSelected(request);const {data,error:responseError}=await db.donations.getResponsesForRequest(request.id);setResponses(data||[]);if(responseError)setError(responseError.message)};
  return <section className="admin-donations">
    <div className="admin-donations-head"><div><h2>Hospital Donation Requests</h2><p>Publish real needs to the patient portal and manage genuine responses.</p></div><div><button className="admin-refresh" onClick={load}><RefreshCw size={17}/>Refresh</button><button className="admin-primary" onClick={()=>setShowForm(true)} disabled={!hospitals.length}><Plus size={18}/>New request</button></div></div>
    <div className="admin-trust-note"><CheckCircle2 size={18}/><span>No demonstration data is generated. A request appears to patients only after an administrator publishes it as active.</span></div>
    {error&&<div className="admin-donation-error"><AlertCircle size={18}/>{error}</div>}
    {loading?<div className="admin-donation-empty">Loading live requests…</div>:requests.length===0?<div className="admin-donation-empty"><HeartHandshake size={42}/><h3>No hospital requests yet</h3><p>Create the first verified request. Until then, patients see an honest empty state.</p></div>:<div className="admin-request-table"><div className="admin-request-row header"><span>Request</span><span>Hospital</span><span>Need</span><span>Status</span><span>Responses</span><span>Actions</span></div>{requests.map(request=><div className="admin-request-row" key={request.id}><span><strong>{request.title}</strong><small>{request.category} · {request.urgency}</small></span><span>{request.hospitals?.name}</span><span>{request.category==='blood'?`${request.units_needed} units ${request.blood_group}`:request.category==='financial'?Number(request.amount_target).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}):request.category}</span><span><b className={`admin-status ${request.status}`}>{request.status}</b></span><span>{request.donation_contributions?.[0]?.count||0}</span><span className="admin-row-actions"><button onClick={()=>viewResponses(request)} title="View patient responses"><Eye size={16}/></button>{request.status==='active'?<><button onClick={()=>changeStatus(request.id,'fulfilled')}>Fulfil</button><button onClick={()=>changeStatus(request.id,'closed')}>Close</button></>:<button onClick={()=>changeStatus(request.id,'active')}>Reopen</button>}</span></div>)}</div>}
    {showForm&&<div className="admin-donation-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false)}}><form className="admin-donation-modal" onSubmit={create}><button type="button" className="admin-modal-x" onClick={()=>setShowForm(false)}><X/></button><h2>Publish verified hospital request</h2><p>Do not include a patient's name, phone number, ABHA number, or other identifying information.</p><div className="admin-form-grid"><label>Hospital<select required value={form.hospitalId} onChange={e=>setForm({...form,hospitalId:e.target.value})}><option value="">Select hospital</option>{hospitals.map(h=><option key={h.id} value={h.id}>{h.name} — {h.city}</option>)}</select></label><label>Request type<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{['blood','financial','equipment','medicine','other'].map(c=><option key={c} value={c}>{c}</option>)}</select></label><label>Urgency<select value={form.urgency} onChange={e=>setForm({...form,urgency:e.target.value})}>{['normal','medium','high','critical'].map(u=><option key={u}>{u}</option>)}</select></label><label>Expires (optional)<input type="datetime-local" value={form.expiresAt} onChange={e=>setForm({...form,expiresAt:e.target.value})}/></label>{form.category==='blood'&&<><label>Blood group<select value={form.bloodGroup} onChange={e=>setForm({...form,bloodGroup:e.target.value})}>{GROUPS.map(g=><option key={g}>{g}</option>)}</select></label><label>Units needed<input required min="1" max="10000" type="number" value={form.unitsNeeded} onChange={e=>setForm({...form,unitsNeeded:e.target.value})}/></label></>}{form.category==='financial'&&<label>Target amount (₹)<input required min="1" type="number" value={form.amountTarget} onChange={e=>setForm({...form,amountTarget:e.target.value})}/></label>}<label className="full">Title<input required minLength="3" maxLength="140" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="full">Description<textarea required minLength="10" maxLength="2000" rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label className="full">Anonymous patient/need summary (optional)<textarea maxLength="500" rows="2" value={form.patientSummary} onChange={e=>setForm({...form,patientSummary:e.target.value})}/></label><label>Location<input maxLength="300" value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>Contact instructions<input maxLength="500" value={form.contactInstructions} onChange={e=>setForm({...form,contactInstructions:e.target.value})}/></label></div><div className="admin-modal-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button className="admin-primary" disabled={saving}>{saving?'Publishing…':'Publish active request'}</button></div></form></div>}
    {selected&&<div className="admin-donation-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><div className="admin-donation-modal"><button className="admin-modal-x" onClick={()=>setSelected(null)}><X/></button><h2>Responses: {selected.title}</h2>{responses.length===0?<div className="admin-donation-empty">No patient has responded yet.</div>:<div className="admin-responses">{responses.map(response=><div key={response.id}><div><strong>{response.patients?.name||'Patient'}</strong><small>{response.patients?.phone||'No phone'} · {new Date(response.created_at).toLocaleString()}</small></div><span>{response.amount_inr?Number(response.amount_inr).toLocaleString('en-IN',{style:'currency',currency:'INR'}):response.units_offered?`${response.units_offered} unit · ${response.blood_group}`:response.contribution_type}<b>{response.status}</b></span>{response.message&&<p>{response.message}</p>}</div>)}</div>}</div></div>}
  </section>;
}
