import React, { useEffect, useMemo, useState } from 'react';
import {
  Activity, AlertCircle, ArrowLeft, Baby, Brain, Check, ChevronRight, Droplet,
  Heart, HeartHandshake, Leaf, MessageCircle, RefreshCw, Ribbon, Search,
  Share2, ShieldCheck, Stethoscope, Users, Wind, X,
} from 'lucide-react';
import { db } from '../lib/db';
import { useLanguage } from '../context/LanguageContext';
import aiTranslationService from '../engine/AiTranslationService';
import '../styles/communities.css';

const THEMES = {
  blood:{color:'#dc2626',soft:'#fff1f2',icon:Droplet}, cancer:{color:'#08765d',soft:'#eaf8f2',icon:Ribbon},
  diabetes:{color:'#7c3aed',soft:'#f5f3ff',icon:Activity}, cardiac:{color:'#e11d48',soft:'#fff1f2',icon:Heart},
  mental:{color:'#7c3aed',soft:'#f4f0ff',icon:Brain}, maternal:{color:'#db2777',soft:'#fdf2f8',icon:Baby},
  senior:{color:'#2563eb',soft:'#eff6ff',icon:Users}, respiratory:{color:'#0284c7',soft:'#f0f9ff',icon:Wind},
  ayush:{color:'#15803d',soft:'#f0fdf4',icon:Leaf}, caregiver:{color:'#ea580c',soft:'#fff7ed',icon:HeartHandshake},
  general:{color:'#087367',soft:'#ecfdf5',icon:Users},
};
const COPY = {
  en:{title:'Communities',subtitle:'Connect, learn and grow with verified health communities.',hero:'Stronger communities, better tomorrow',heroText:'Join condition-specific spaces, learn from verified professionals and support one another.',impact:'Live community impact',members:'Real members',posts:'Verified posts',responses:'Helpful responses',experts:'Connected experts',search:'Search communities or health topics',all:'All categories',view:'View community',join:'Join community',joined:'Joined',leave:'Leave community',back:'All communities',verified:'Verified community',doctorPosts:'Doctor and expert guidance',noCommunities:'No active communities found',noCommunitiesText:'Communities published in the database will appear here automatically.',noPosts:'No verified posts yet',noPostsText:'This feed will update when a related verified doctor publishes guidance.',refresh:'Refresh',helpful:'Helpful',comments:'Comments',share:'Share',writeComment:'Write a respectful comment…',send:'Post comment',joinToInteract:'Join this community to react or comment.',loading:'Loading live community data…',error:'Unable to load community data.',copied:'Community link copied.',specialities:'Relevant medical specialities',close:'Close'},
  hi:{title:'समुदाय',subtitle:'सत्यापित स्वास्थ्य समुदायों से जुड़ें, सीखें और आगे बढ़ें।',hero:'मजबूत समुदाय, बेहतर कल',heroText:'रोग-विशेष समूहों से जुड़ें, सत्यापित विशेषज्ञों से सीखें और एक-दूसरे की सहायता करें।',impact:'लाइव समुदाय प्रभाव',members:'वास्तविक सदस्य',posts:'सत्यापित पोस्ट',responses:'सहायक प्रतिक्रियाएँ',experts:'जुड़े विशेषज्ञ',search:'समुदाय या स्वास्थ्य विषय खोजें',all:'सभी श्रेणियाँ',view:'समुदाय देखें',join:'समुदाय से जुड़ें',joined:'जुड़ गए',leave:'समुदाय छोड़ें',back:'सभी समुदाय',verified:'सत्यापित समुदाय',doctorPosts:'डॉक्टर और विशेषज्ञ मार्गदर्शन',noCommunities:'कोई सक्रिय समुदाय नहीं मिला',noCommunitiesText:'डेटाबेस में प्रकाशित समुदाय यहाँ अपने-आप दिखाई देंगे।',noPosts:'अभी कोई सत्यापित पोस्ट नहीं है',noPostsText:'संबंधित सत्यापित डॉक्टर के मार्गदर्शन प्रकाशित करते ही यह फीड अपडेट होगी।',refresh:'रीफ्रेश',helpful:'सहायक',comments:'टिप्पणियाँ',share:'साझा करें',writeComment:'सम्मानजनक टिप्पणी लिखें…',send:'टिप्पणी भेजें',joinToInteract:'प्रतिक्रिया या टिप्पणी करने के लिए समुदाय से जुड़ें।',loading:'लाइव समुदाय डेटा लोड हो रहा है…',error:'समुदाय डेटा लोड नहीं हो सका।',copied:'समुदाय लिंक कॉपी हो गया।',specialities:'संबंधित चिकित्सा विशेषज्ञताएँ',close:'बंद करें'},
};
const SHORT_COPY={ta:{title:'சமூகங்கள்',join:'சமூகத்தில் சேரவும்',joined:'இணைந்தது',leave:'சமூகத்திலிருந்து விலகவும்',view:'சமூகத்தைக் காண்க',search:'சமூகங்கள் அல்லது சுகாதார தலைப்புகளைத் தேடுங்கள்',back:'அனைத்து சமூகங்கள்',helpful:'பயனுள்ளது',comments:'கருத்துகள்',share:'பகிரவும்',send:'கருத்தை இடுக'},te:{title:'కమ్యూనిటీలు',join:'కమ్యూనిటీలో చేరండి',joined:'చేరారు',leave:'కమ్యూనిటీని వీడండి',view:'కమ్యూనిటీని చూడండి',search:'కమ్యూనిటీలు లేదా ఆరోగ్య అంశాలను వెతకండి',back:'అన్ని కమ్యూనిటీలు',helpful:'సహాయకరం',comments:'వ్యాఖ్యలు',share:'పంచుకోండి',send:'వ్యాఖ్య పంపండి'},bn:{title:'কমিউনিটি',join:'কমিউনিটিতে যোগ দিন',joined:'যোগ দিয়েছেন',leave:'কমিউনিটি ছাড়ুন',view:'কমিউনিটি দেখুন',search:'কমিউনিটি বা স্বাস্থ্য বিষয় খুঁজুন',back:'সব কমিউনিটি',helpful:'সহায়ক',comments:'মন্তব্য',share:'শেয়ার',send:'মন্তব্য পাঠান'},mr:{title:'समुदाय',join:'समुदायात सामील व्हा',joined:'सामील',leave:'समुदाय सोडा',view:'समुदाय पहा',search:'समुदाय किंवा आरोग्य विषय शोधा',back:'सर्व समुदाय',helpful:'उपयुक्त',comments:'टिप्पण्या',share:'शेअर',send:'टिप्पणी पाठवा'},gu:{title:'સમુદાયો',join:'સમુદાયમાં જોડાઓ',joined:'જોડાયા',leave:'સમુદાય છોડો',view:'સમુદાય જુઓ',search:'સમુદાય અથવા આરોગ્ય વિષય શોધો',back:'બધા સમુદાયો',helpful:'મદદરૂપ',comments:'ટિપ્પણીઓ',share:'શેર',send:'ટિપ્પણી મોકલો'},kn:{title:'ಸಮುದಾಯಗಳು',join:'ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',joined:'ಸೇರಿದ್ದೀರಿ',leave:'ಸಮುದಾಯ ತೊರೆಯಿರಿ',view:'ಸಮುದಾಯ ನೋಡಿ',search:'ಸಮುದಾಯ ಅಥವಾ ಆರೋಗ್ಯ ವಿಷಯ ಹುಡುಕಿ',back:'ಎಲ್ಲಾ ಸಮುದಾಯಗಳು',helpful:'ಸಹಾಯಕ',comments:'ಕಾಮೆಂಟ್‌ಗಳು',share:'ಹಂಚಿಕೊಳ್ಳಿ',send:'ಕಾಮೆಂಟ್ ಕಳುಹಿಸಿ'},ml:{title:'കമ്മ്യൂണിറ്റികൾ',join:'കമ്മ്യൂണിറ്റിയിൽ ചേരുക',joined:'ചേർന്നു',leave:'കമ്മ്യൂണിറ്റി വിടുക',view:'കമ്മ്യൂണിറ്റി കാണുക',search:'കമ്മ്യൂണിറ്റി അല്ലെങ്കിൽ ആരോഗ്യ വിഷയം തിരയുക',back:'എല്ലാ കമ്മ്യൂണിറ്റികളും',helpful:'സഹായകരം',comments:'അഭിപ്രായങ്ങൾ',share:'പങ്കിടുക',send:'അഭിപ്രായം അയയ്ക്കുക'}};

const countOf=(row,key)=>Number(row?.[key]?.[0]?.count||0);
const displayName=(name='Community member')=>name.trim().split(/\s+/)[0]||'Member';
const localText=(row,key,lang)=>row?.[`${key}_i18n`]?.[lang]||(lang==='en'?row?.[key]:aiTranslationService.translate(row?.[key]||'',lang,'general'))||'';
const formatCount=value=>new Intl.NumberFormat('en-IN',{notation:value>=10000?'compact':'standard',maximumFractionDigits:1}).format(value||0);
function timeAgo(value,lang){const delta=Math.round((new Date(value).getTime()-Date.now())/1000);const f=new Intl.RelativeTimeFormat(lang||'en',{numeric:'auto'});if(Math.abs(delta)<3600)return f.format(Math.round(delta/60),'minute');if(Math.abs(delta)<86400)return f.format(Math.round(delta/3600),'hour');return f.format(Math.round(delta/86400),'day')}

export default function CommunitiesTab({patientId}){
  const {currentLang}=useLanguage();
  const explicit={...(COPY[currentLang]||{}),...(SHORT_COPY[currentLang]||{})};
  const tr=Object.fromEntries(Object.entries(COPY.en).map(([key,value])=>[key,explicit[key]||(currentLang==='en'?value:aiTranslationService.translate(value,currentLang,'general'))]));
  const [,setTranslationTick]=useState(0);
  useEffect(()=>aiTranslationService.subscribe(()=>setTranslationTick(value=>value+1)),[]);
  const [communities,setCommunities]=useState([]),[joined,setJoined]=useState([]),[selected,setSelected]=useState(null),[posts,setPosts]=useState([]),[reactions,setReactions]=useState({});
  const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[loading,setLoading]=useState(true),[feedLoading,setFeedLoading]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('');
  const [impact,setImpact]=useState({members:0,posts:0,reactions:0,experts:0});
  const [commentPost,setCommentPost]=useState(null),[comments,setComments]=useState([]),[comment,setComment]=useState(''),[commentLoading,setCommentLoading]=useState(false);

  // Voice feedback for community chat group
  useEffect(() => {
    if (selected) {
      import('../voicenav/AudioPromptManager').then(module => {
        module.default.interruptWith(tr.view || 'View community');
      }).catch(err => console.error('Failed to load AudioPromptManager for CommunitiesTab', err));
    }
  }, [selected, tr.view]);
  const loadDirectory=async()=>{setLoading(true);setError('');const [{data,error:dirError},{data:members,error:memberError},{data:liveImpact,error:impactError}]=await Promise.all([db.communities.getDirectory(),db.communities.getMemberships(patientId),db.communities.getImpact()]);setCommunities(data||[]);setJoined((members||[]).map(item=>item.community_id));setImpact(liveImpact||{members:0,posts:0,reactions:0,experts:0});if(dirError||memberError||impactError)setError((dirError||memberError||impactError).message);setLoading(false)};
  useEffect(()=>{loadDirectory()},[patientId]); // eslint-disable-line react-hooks/exhaustive-deps
  const openCommunity=async community=>{setSelected(community);setFeedLoading(true);setError('');const {data,error:postError}=await db.communities.getPosts(community.id);setPosts(data||[]);if(postError)setError(postError.message);else{const {data:mine}=await db.communities.getPatientReactions(patientId,(data||[]).map(post=>post.id));setReactions(Object.fromEntries((mine||[]).map(item=>[item.post_id,item.reaction_type])))}setFeedLoading(false)};
  const toggleMembership=async community=>{const isJoined=joined.includes(community.id);const {error:joinError}=await db.communities.setMembership(patientId,community.id,!isJoined);if(joinError){setError(joinError.message);return}setJoined(current=>isJoined?current.filter(id=>id!==community.id):[...current,community.id]);setCommunities(current=>current.map(item=>item.id===community.id?{...item,patient_community_memberships:[{count:Math.max(0,countOf(item,'patient_community_memberships')+(isJoined?-1:1))}]}:item));setSelected(current=>current?.id===community.id?{...current,patient_community_memberships:[{count:Math.max(0,countOf(current,'patient_community_memberships')+(isJoined?-1:1))}]}:current)};
  const toggleReaction=async post=>{if(!joined.includes(post.community_id)){setToast(tr.joinToInteract);return}const had=Boolean(reactions[post.id]);const {data,error:reactionError}=await db.communities.toggleReaction(patientId,post.id);if(reactionError){setError(reactionError.message);return}setReactions(current=>({...current,[post.id]:data?'helpful':undefined}));setPosts(current=>current.map(item=>item.id===post.id?{...item,community_post_reactions:[{count:Math.max(0,countOf(item,'community_post_reactions')+(had?-1:1))}]}:item))};
  const openComments=async post=>{setCommentPost(post);setCommentLoading(true);setComment('');const {data,error:commentsError}=await db.communities.getComments(post.id);setComments(data||[]);if(commentsError)setError(commentsError.message);setCommentLoading(false)};
  const submitComment=async event=>{event.preventDefault();if(!joined.includes(commentPost.community_id)){setToast(tr.joinToInteract);return}const {error:commentError}=await db.communities.addComment(patientId,commentPost.id,comment);if(commentError){setError(commentError.message);return}setComment('');const {data}=await db.communities.getComments(commentPost.id);setComments(data||[]);setPosts(current=>current.map(item=>item.id===commentPost.id?{...item,community_post_comments:[{count:countOf(item,'community_post_comments')+1}]}:item))};
  const share=async community=>{const url=`${window.location.origin}${window.location.pathname}#community-${community.id}`;try{if(navigator.share)await navigator.share({title:community.title,text:community.description,url});else await navigator.clipboard.writeText(url);setToast(tr.copied)}catch(error){if(error?.name!=='AbortError')setError(error.message)}};
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),2600);return()=>clearTimeout(timer)},[toast]);
  const categories=useMemo(()=>['all',...new Set(communities.map(item=>item.category).filter(Boolean))],[communities]);
  const filtered=useMemo(()=>communities.filter(item=>(category==='all'||item.category===category)&&`${localText(item,'title',currentLang)} ${localText(item,'description',currentLang)} ${item.category||''} ${(item.eligible_specialities||[]).join(' ')}`.toLowerCase().includes(query.trim().toLowerCase())),[communities,category,query,currentLang]);

  if(selected){const theme=THEMES[selected.theme_key]||THEMES.general,Icon=theme.icon,isJoined=joined.includes(selected.id);return <section className="community-detail" style={{'--community-color':theme.color,'--community-soft':theme.soft}}>
    <button className="community-back" onClick={()=>{setSelected(null);setPosts([])}}><ArrowLeft size={17}/>{tr.back}</button>
    <div className="community-detail-hero"><div className="community-detail-icon"><Icon size={58}/></div><div className="community-detail-copy"><span className="verified-community"><ShieldCheck size={15}/>{tr.verified}</span><h1>{localText(selected,'title',currentLang)}</h1><h2>{localText(selected,'tagline',currentLang)}</h2><p>{localText(selected,'description',currentLang)}</p><div className="community-detail-stats"><span><Users size={19}/><b>{formatCount(countOf(selected,'patient_community_memberships'))}</b>{tr.members}</span><span><Stethoscope size={19}/><b>{formatCount(countOf(selected,'community_professionals'))}</b>{tr.experts}</span><span><MessageCircle size={19}/><b>{formatCount(countOf(selected,'community_posts'))}</b>{tr.posts}</span></div></div><div className="community-detail-actions"><button className={isJoined?'joined':''} onClick={()=>toggleMembership(selected)}>{isJoined?<Check size={17}/>:<Users size={17}/>} {isJoined?tr.joined:tr.join}</button><button onClick={()=>share(selected)}><Share2 size={17}/>{tr.share}</button></div></div>
    {!!selected.eligible_specialities?.length&&<div className="community-specialities"><Stethoscope size={18}/><strong>{tr.specialities}:</strong>{selected.eligible_specialities.map(item=><span key={item}>{item}</span>)}</div>}
    <div className="community-feed-heading"><div><h2>{tr.doctorPosts}</h2><p>{localText(selected,'tagline',currentLang)}</p></div><button onClick={()=>openCommunity(selected)}><RefreshCw size={16}/>{tr.refresh}</button></div>
    {error&&<div className="community-alert"><AlertCircle size={18}/>{tr.error} {error}</div>}
    {feedLoading?<div className="community-empty"><RefreshCw className="spin"/><h3>{tr.loading}</h3></div>:posts.length===0?<div className="community-empty"><Stethoscope size={45}/><h3>{tr.noPosts}</h3><p>{tr.noPostsText}</p></div>:<div className="community-feed">{posts.map(post=>{const translation=post.translations?.[currentLang];const body=translation?.body||(currentLang==='en'?post.body:aiTranslationService.translate(post.body,currentLang,'general')),title=translation?.title||(currentLang==='en'?post.title:aiTranslationService.translate(post.title||'',currentLang,'general')),doctor=post.doctors;return <article className="community-post" key={post.id}><div className="post-author"><div className="doctor-avatar">{doctor?.avatar_url?<img src={doctor.avatar_url} alt=""/>:<Stethoscope/>}</div><div><strong>{doctor?.name||tr.verified}<ShieldCheck size={15}/></strong><span>{[doctor?.speciality,doctor?.hospitals?.name,doctor?.hospitals?.city].filter(Boolean).join(' · ')}</span><small>{timeAgo(post.published_at||post.created_at,currentLang)}</small></div><b>{post.post_type}</b></div>{title&&<h3>{title}</h3>}<p>{body}</p>{post.media_url&&<img className="post-media" src={post.media_url} alt={post.media_alt||title||tr.doctorPosts}/>}<div className="post-actions"><button className={reactions[post.id]?'active':''} onClick={()=>toggleReaction(post)}><Heart size={19} fill={reactions[post.id]?'currentColor':'none'}/>{formatCount(countOf(post,'community_post_reactions'))} {tr.helpful}</button><button onClick={()=>openComments(post)}><MessageCircle size={19}/>{formatCount(countOf(post,'community_post_comments'))} {tr.comments}</button><button onClick={()=>share(selected)}><Share2 size={19}/>{tr.share}</button></div></article>})}</div>}
    {commentPost&&<div className="community-modal-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setCommentPost(null)}}><div className="community-comments-modal"><button className="community-modal-close" onClick={()=>setCommentPost(null)} aria-label={tr.close}><X/></button><h2>{tr.comments}</h2>{commentLoading?<div className="comment-state">{tr.loading}</div>:comments.length===0?<div className="comment-state">{tr.comments}: 0</div>:<div className="comment-list">{comments.map(item=><div key={item.id}><span>{displayName(item.patients?.name)}</span><p>{item.body}</p><small>{timeAgo(item.created_at,currentLang)}</small></div>)}</div>}{isJoined?<form onSubmit={submitComment}><textarea required maxLength="2000" rows="3" placeholder={tr.writeComment} value={comment} onChange={event=>setComment(event.target.value)}/><button>{tr.send}</button></form>:<div className="join-to-comment">{tr.joinToInteract}</div>}</div></div>}
    {toast&&<div className="community-toast">{toast}</div>}
  </section>}

  return <section className="communities-page"><div className="communities-heading"><span>Patient Portal / {tr.title}</span><h1>{tr.title}</h1><p>{tr.subtitle}</p></div><div className="communities-hero"><div><h2>{tr.hero} <Heart size={25} fill="currentColor"/></h2><p>{tr.heroText}</p></div><div className="community-impact"><h3>{tr.impact}</h3><div><span><Users/><b>{formatCount(impact.members)}</b><small>{tr.members}</small></span><span><MessageCircle/><b>{formatCount(impact.posts)}</b><small>{tr.posts}</small></span><span><HeartHandshake/><b>{formatCount(impact.reactions)}</b><small>{tr.responses}</small></span><span><Stethoscope/><b>{formatCount(impact.experts)}</b><small>{tr.experts}</small></span></div></div></div>
    <div className="community-directory-title"><h2>{tr.title}</h2><button onClick={loadDirectory}><RefreshCw size={16}/>{tr.refresh}</button></div><div className="community-filters"><label><Search size={19}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={tr.search}/></label><select value={category} onChange={event=>setCategory(event.target.value)}>{categories.map(item=><option key={item} value={item}>{item==='all'?tr.all:item}</option>)}</select></div>
    {error&&<div className="community-alert"><AlertCircle size={18}/>{tr.error} {error}</div>}{loading?<div className="community-empty"><RefreshCw className="spin"/><h3>{tr.loading}</h3></div>:filtered.length===0?<div className="community-empty"><Users size={45}/><h3>{tr.noCommunities}</h3><p>{tr.noCommunitiesText}</p></div>:<div className="community-grid">{filtered.map(item=>{const theme=THEMES[item.theme_key]||THEMES.general,Icon=theme.icon,isJoined=joined.includes(item.id);return <article key={item.id} className="community-card" style={{'--card-color':theme.color,'--card-soft':theme.soft}}><div className="community-card-icon"><Icon size={38}/></div>{item.is_verified&&<span className="card-verified"><ShieldCheck size={13}/>{tr.verified}</span>}<h3>{localText(item,'title',currentLang)}</h3><b>{localText(item,'tagline',currentLang)}</b><p>{localText(item,'description',currentLang)}</p><div className="community-card-counts"><span><Users size={16}/>{formatCount(countOf(item,'patient_community_memberships'))} {tr.members}</span><span><MessageCircle size={16}/>{formatCount(countOf(item,'community_posts'))} {tr.posts}</span></div><div className="community-card-actions"><button className="view" onClick={()=>openCommunity(item)}>{tr.view}<ChevronRight size={16}/></button><button className={isJoined?'joined':''} onClick={()=>toggleMembership(item)}>{isJoined?<Check size={16}/>:<Users size={16}/>} {isJoined?tr.joined:tr.join}</button></div></article>})}</div>}{toast&&<div className="community-toast">{toast}</div>}
  </section>;
}
