import React, { useEffect, useMemo, useState } from 'react';
import { AlertCircle, CheckCircle2, Clock3, Droplet, HeartHandshake, IndianRupee, MapPin, Package, Pill, RefreshCw, Search, ShieldCheck, X } from 'lucide-react';
import { db } from '../lib/db';
import { useLanguage } from '../context/LanguageContext';
import aiTranslationService from '../engine/AiTranslationService';
import '../styles/donations.css';

const GROUPS = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];
const DONOR_COMPATIBILITY = { 'O-': GROUPS, 'O+': ['O+', 'A+', 'B+', 'AB+'], 'A-': ['A-', 'A+', 'AB-', 'AB+'], 'A+': ['A+', 'AB+'], 'B-': ['B-', 'B+', 'AB-', 'AB+'], 'B+': ['B+', 'AB+'], 'AB-': ['AB-', 'AB+'], 'AB+': ['AB+'] };
const COPY = {
  en: { title: 'Donations', subtitle: 'Respond to verified needs published by hospitals.', hero: 'Your support, their tomorrow', heroText: 'Every request below comes directly from a hospital administrator. No sample requests are shown.', all: 'All requests', blood: 'Blood', financial: 'Financial', equipment: 'Equipment', medicine: 'Medicine', other: 'Other', search: 'Search hospital, city or request', empty: 'No active requests right now', emptyText: 'Hospital requests will appear here automatically when an administrator publishes them.', retry: 'Refresh', history: 'My responses', contributed: 'Money pledged', responses: 'Responses made', active: 'Awaiting hospital', view: 'Respond', selectBlood: 'Select your blood group', matching: 'Compatible blood requests', noMatch: 'No compatible active blood request is available.', amount: 'Pledge amount (₹)', units: 'Units you can offer', message: 'Message for hospital (optional)', submit: 'Submit response', cancel: 'Cancel', disclaimer: 'This records a pledge/contact request only. No payment is charged on this website.', success: 'Your response was saved and is now visible to the hospital.', loading: 'Loading live requests…', error: 'Unable to load live donation data.', posted: 'Posted', target: 'Target', needed: 'needed', location: 'Location not specified', close: 'Close' },
  hi: { title: 'दान और सहायता', subtitle: 'अस्पतालों द्वारा प्रकाशित सत्यापित जरूरतों पर सहायता दें।', hero: 'आपका सहयोग, उनका बेहतर कल', heroText: 'नीचे हर अनुरोध सीधे अस्पताल प्रशासक से आता है। कोई नमूना डेटा नहीं दिखाया जाता।', all: 'सभी अनुरोध', blood: 'रक्त', financial: 'आर्थिक', equipment: 'उपकरण', medicine: 'दवाइयाँ', other: 'अन्य', search: 'अस्पताल, शहर या अनुरोध खोजें', empty: 'अभी कोई सक्रिय अनुरोध नहीं है', emptyText: 'अस्पताल प्रशासक के प्रकाशित करते ही अनुरोध यहाँ दिखाई देगा।', retry: 'रीफ्रेश करें', history: 'मेरी प्रतिक्रियाएँ', contributed: 'वचनबद्ध राशि', responses: 'कुल प्रतिक्रियाएँ', active: 'अस्पताल की प्रतीक्षा', view: 'सहायता दें', selectBlood: 'अपना रक्त समूह चुनें', matching: 'अनुकूल रक्त अनुरोध', noMatch: 'अभी कोई अनुकूल सक्रिय रक्त अनुरोध नहीं है।', amount: 'वचन राशि (₹)', units: 'आप कितनी यूनिट दे सकते हैं', message: 'अस्पताल के लिए संदेश (वैकल्पिक)', submit: 'प्रतिक्रिया भेजें', cancel: 'रद्द करें', disclaimer: 'यह केवल वचन/संपर्क अनुरोध दर्ज करता है। वेबसाइट पर कोई भुगतान नहीं कटेगा।', success: 'आपकी प्रतिक्रिया सहेज दी गई है और अस्पताल को दिखाई देगी।', loading: 'लाइव अनुरोध लोड हो रहे हैं…', error: 'लाइव दान डेटा लोड नहीं हो सका।', posted: 'प्रकाशित', target: 'लक्ष्य', needed: 'आवश्यक', location: 'स्थान उपलब्ध नहीं', close: 'बंद करें' },
  ta: { title:'நன்கொடைகள்', subtitle:'மருத்துவமனைகள் வெளியிட்ட சரிபார்க்கப்பட்ட தேவைகளுக்கு உதவுங்கள்.', hero:'உங்கள் ஆதரவு, அவர்களின் நாளை', heroText:'ஒவ்வொரு கோரிக்கையும் மருத்துவமனை நிர்வாகியிடமிருந்து நேரடியாக வருகிறது. மாதிரி தரவு காட்டப்படாது.', all:'அனைத்து கோரிக்கைகள்', blood:'இரத்தம்', financial:'நிதி', equipment:'உபகரணங்கள்', medicine:'மருந்துகள்', other:'மற்றவை', search:'மருத்துவமனை, நகரம் அல்லது கோரிக்கையைத் தேடுங்கள்', empty:'இப்போது செயலில் கோரிக்கைகள் இல்லை', retry:'புதுப்பிக்கவும்', history:'என் பதில்கள்', view:'பதிலளிக்கவும்', selectBlood:'உங்கள் இரத்த வகையைத் தேர்ந்தெடுக்கவும்', amount:'உறுதி தொகை (₹)', units:'நீங்கள் வழங்கக்கூடிய அலகுகள்', message:'மருத்துவமனைக்கான செய்தி (விருப்பம்)', submit:'பதிலை அனுப்பவும்', cancel:'ரத்து', loading:'நேரடி கோரிக்கைகள் ஏற்றப்படுகின்றன…', close:'மூடு' },
  te: { title:'విరాళాలు', subtitle:'ఆసుపత్రులు ప్రచురించిన ధృవీకరించిన అవసరాలకు సహాయం చేయండి.', hero:'మీ సహాయం, వారి రేపు', heroText:'ప్రతి అభ్యర్థన నేరుగా ఆసుపత్రి నిర్వాహకుడి నుంచే వస్తుంది. నమూనా డేటా చూపబడదు.', all:'అన్ని అభ్యర్థనలు', blood:'రక్తం', financial:'ఆర్థిక', equipment:'పరికరాలు', medicine:'మందులు', other:'ఇతర', search:'ఆసుపత్రి, నగరం లేదా అభ్యర్థనను వెతకండి', empty:'ప్రస్తుతం క్రియాశీల అభ్యర్థనలు లేవు', retry:'రిఫ్రెష్', history:'నా స్పందనలు', view:'స్పందించండి', selectBlood:'మీ రక్త వర్గాన్ని ఎంచుకోండి', amount:'హామీ మొత్తం (₹)', units:'మీరు ఇవ్వగల యూనిట్లు', message:'ఆసుపత్రికి సందేశం (ఐచ్ఛికం)', submit:'స్పందన పంపండి', cancel:'రద్దు', loading:'ప్రత్యక్ష అభ్యర్థనలు లోడ్ అవుతున్నాయి…', close:'మూసివేయండి' },
  bn: { title:'দান ও সহায়তা', subtitle:'হাসপাতাল প্রকাশিত যাচাইকৃত প্রয়োজনে সাড়া দিন।', hero:'আপনার সহায়তা, তাদের আগামীকাল', heroText:'প্রতিটি অনুরোধ সরাসরি হাসপাতাল প্রশাসকের কাছ থেকে আসে। কোনো নমুনা তথ্য দেখানো হয় না।', all:'সব অনুরোধ', blood:'রক্ত', financial:'আর্থিক', equipment:'সরঞ্জাম', medicine:'ওষুধ', other:'অন্যান্য', search:'হাসপাতাল, শহর বা অনুরোধ খুঁজুন', empty:'এখন কোনো সক্রিয় অনুরোধ নেই', retry:'রিফ্রেশ', history:'আমার প্রতিক্রিয়া', view:'সাড়া দিন', selectBlood:'আপনার রক্তের গ্রুপ বেছে নিন', amount:'প্রতিশ্রুত অর্থ (₹)', units:'আপনি যত ইউনিট দিতে পারবেন', message:'হাসপাতালের জন্য বার্তা (ঐচ্ছিক)', submit:'প্রতিক্রিয়া পাঠান', cancel:'বাতিল', loading:'লাইভ অনুরোধ লোড হচ্ছে…', close:'বন্ধ করুন' },
  mr: { title:'देणगी आणि मदत', subtitle:'रुग्णालयांनी प्रकाशित केलेल्या पडताळलेल्या गरजांना प्रतिसाद द्या.', hero:'तुमचा आधार, त्यांचा उद्याचा दिवस', heroText:'प्रत्येक विनंती थेट रुग्णालय प्रशासकाकडून येते. नमुना डेटा दाखवला जात नाही.', all:'सर्व विनंत्या', blood:'रक्त', financial:'आर्थिक', equipment:'उपकरणे', medicine:'औषधे', other:'इतर', search:'रुग्णालय, शहर किंवा विनंती शोधा', empty:'सध्या कोणतीही सक्रिय विनंती नाही', retry:'रीफ्रेश', history:'माझे प्रतिसाद', view:'प्रतिसाद द्या', selectBlood:'तुमचा रक्तगट निवडा', amount:'वचन रक्कम (₹)', units:'तुम्ही देऊ शकणारी युनिट्स', message:'रुग्णालयासाठी संदेश (ऐच्छिक)', submit:'प्रतिसाद पाठवा', cancel:'रद्द करा', loading:'थेट विनंत्या लोड होत आहेत…', close:'बंद करा' },
  gu: { title:'દાન અને સહાય', subtitle:'હોસ્પિટલો દ્વારા પ્રકાશિત ચકાસાયેલ જરૂરિયાતોને પ્રતિસાદ આપો.', hero:'તમારો સહયોગ, તેમનું આવતીકાલ', heroText:'દરેક વિનંતી સીધી હોસ્પિટલ સંચાલક તરફથી આવે છે. નમૂનાનો ડેટા બતાવવામાં આવતો નથી.', all:'બધી વિનંતીઓ', blood:'રક્ત', financial:'આર્થિક', equipment:'સાધનો', medicine:'દવાઓ', other:'અન્ય', search:'હોસ્પિટલ, શહેર અથવા વિનંતી શોધો', empty:'હાલ કોઈ સક્રિય વિનંતી નથી', retry:'રિફ્રેશ', history:'મારા પ્રતિસાદ', view:'પ્રતિસાદ આપો', selectBlood:'તમારું રક્ત જૂથ પસંદ કરો', amount:'વચન રકમ (₹)', units:'તમે આપી શકો તે યુનિટ', message:'હોસ્પિટલ માટે સંદેશ (વૈકલ્પિક)', submit:'પ્રતિસાદ મોકલો', cancel:'રદ કરો', loading:'લાઇવ વિનંતીઓ લોડ થઈ રહી છે…', close:'બંધ કરો' },
  kn: { title:'ದೇಣಿಗೆಗಳು', subtitle:'ಆಸ್ಪತ್ರೆಗಳು ಪ್ರಕಟಿಸಿದ ಪರಿಶೀಲಿತ ಅಗತ್ಯಗಳಿಗೆ ಸ್ಪಂದಿಸಿ.', hero:'ನಿಮ್ಮ ಬೆಂಬಲ, ಅವರ ನಾಳೆ', heroText:'ಪ್ರತಿ ವಿನಂತಿಯೂ ನೇರವಾಗಿ ಆಸ್ಪತ್ರೆಯ ನಿರ್ವಾಹಕರಿಂದ ಬರುತ್ತದೆ. ಮಾದರಿ ಡೇಟಾವನ್ನು ತೋರಿಸಲಾಗುವುದಿಲ್ಲ.', all:'ಎಲ್ಲಾ ವಿನಂತಿಗಳು', blood:'ರಕ್ತ', financial:'ಹಣಕಾಸು', equipment:'ಉಪಕರಣ', medicine:'ಔಷಧಿ', other:'ಇತರೆ', search:'ಆಸ್ಪತ್ರೆ, ನಗರ ಅಥವಾ ವಿನಂತಿಯನ್ನು ಹುಡುಕಿ', empty:'ಈಗ ಯಾವುದೇ ಸಕ್ರಿಯ ವಿನಂತಿಗಳಿಲ್ಲ', retry:'ರಿಫ್ರೆಶ್', history:'ನನ್ನ ಪ್ರತಿಕ್ರಿಯೆಗಳು', view:'ಪ್ರತಿಕ್ರಿಯಿಸಿ', selectBlood:'ನಿಮ್ಮ ರಕ್ತದ ಗುಂಪನ್ನು ಆಯ್ಕೆಮಾಡಿ', amount:'ವಾಗ್ದಾನ ಮೊತ್ತ (₹)', units:'ನೀವು ನೀಡಬಹುದಾದ ಯೂನಿಟ್‌ಗಳು', message:'ಆಸ್ಪತ್ರೆಗೆ ಸಂದೇಶ (ಐಚ್ಛಿಕ)', submit:'ಪ್ರತಿಕ್ರಿಯೆ ಕಳುಹಿಸಿ', cancel:'ರದ್ದುಮಾಡಿ', loading:'ಲೈವ್ ವಿನಂತಿಗಳು ಲೋಡ್ ಆಗುತ್ತಿವೆ…', close:'ಮುಚ್ಚಿ' },
  ml: { title:'സംഭാവനകൾ', subtitle:'ആശുപത്രികൾ പ്രസിദ്ധീകരിച്ച പരിശോധിച്ച ആവശ്യങ്ങളോട് പ്രതികരിക്കുക.', hero:'നിങ്ങളുടെ പിന്തുണ, അവരുടെ നാളെ', heroText:'ഓരോ അഭ്യർത്ഥനയും ആശുപത്രി അഡ്മിനിസ്ട്രേറ്ററിൽ നിന്ന് നേരിട്ട് വരുന്നു. മാതൃകാ ഡാറ്റ കാണിക്കില്ല.', all:'എല്ലാ അഭ്യർത്ഥനകളും', blood:'രക്തം', financial:'സാമ്പത്തികം', equipment:'ഉപകരണങ്ങൾ', medicine:'മരുന്നുകൾ', other:'മറ്റുള്ളവ', search:'ആശുപത്രി, നഗരം അല്ലെങ്കിൽ അഭ്യർത്ഥന തിരയുക', empty:'ഇപ്പോൾ സജീവ അഭ്യർത്ഥനകളില്ല', retry:'പുതുക്കുക', history:'എന്റെ പ്രതികരണങ്ങൾ', view:'പ്രതികരിക്കുക', selectBlood:'നിങ്ങളുടെ രക്തഗ്രൂപ്പ് തിരഞ്ഞെടുക്കുക', amount:'വാഗ്ദാന തുക (₹)', units:'നിങ്ങൾക്ക് നൽകാവുന്ന യൂണിറ്റുകൾ', message:'ആശുപത്രിക്കുള്ള സന്ദേശം (ഓപ്ഷണൽ)', submit:'പ്രതികരണം അയയ്ക്കുക', cancel:'റദ്ദാക്കുക', loading:'ലൈവ് അഭ്യർത്ഥനകൾ ലോഡ് ചെയ്യുന്നു…', close:'അടയ്ക്കുക' },
};
Object.assign(COPY.ta,{emptyText:'மருத்துவமனை நிர்வாகி வெளியிட்டவுடன் கோரிக்கைகள் இங்கே தானாக தோன்றும்.',contributed:'உறுதியளித்த தொகை',responses:'அனுப்பிய பதில்கள்',active:'மருத்துவமனை பதிலுக்காக',matching:'பொருந்தும் இரத்த கோரிக்கைகள்',noMatch:'பொருந்தும் செயலில் உள்ள இரத்த கோரிக்கை இல்லை.',disclaimer:'இது உறுதி அல்லது தொடர்பு கோரிக்கையை மட்டும் பதிவு செய்கிறது. இந்த இணையதளத்தில் பணம் வசூலிக்கப்படாது.',success:'உங்கள் பதில் சேமிக்கப்பட்டு மருத்துவமனைக்கு காணப்படுகிறது.',error:'நேரடி நன்கொடை தரவை ஏற்ற முடியவில்லை.',posted:'வெளியிடப்பட்டது',target:'இலக்கு',needed:'தேவை',location:'இடம் குறிப்பிடப்படவில்லை'});
Object.assign(COPY.te,{emptyText:'ఆసుపత్రి నిర్వాహకుడు ప్రచురించిన వెంటనే అభ్యర్థనలు ఇక్కడ కనిపిస్తాయి.',contributed:'హామీ ఇచ్చిన మొత్తం',responses:'పంపిన స్పందనలు',active:'ఆసుపత్రి స్పందన కోసం',matching:'సరిపోలే రక్త అభ్యర్థనలు',noMatch:'సరిపోలే క్రియాశీల రక్త అభ్యర్థన లేదు.',disclaimer:'ఇది హామీ లేదా సంప్రదింపు అభ్యర్థనను మాత్రమే నమోదు చేస్తుంది. ఈ వెబ్‌సైట్‌లో చెల్లింపు తీసుకోబడదు.',success:'మీ స్పందన సేవ్ అయి ఆసుపత్రికి కనిపిస్తుంది.',error:'ప్రత్యక్ష విరాళ డేటాను లోడ్ చేయలేకపోయాము.',posted:'ప్రచురించబడింది',target:'లక్ష్యం',needed:'అవసరం',location:'స్థానం పేర్కొనలేదు'});
Object.assign(COPY.bn,{emptyText:'হাসপাতাল প্রশাসক প্রকাশ করলেই অনুরোধ এখানে দেখা যাবে।',contributed:'প্রতিশ্রুত অর্থ',responses:'পাঠানো প্রতিক্রিয়া',active:'হাসপাতালের উত্তরের অপেক্ষায়',matching:'সামঞ্জস্যপূর্ণ রক্তের অনুরোধ',noMatch:'কোনো সামঞ্জস্যপূর্ণ সক্রিয় রক্তের অনুরোধ নেই।',disclaimer:'এটি শুধু প্রতিশ্রুতি বা যোগাযোগের অনুরোধ নথিভুক্ত করে। এই ওয়েবসাইটে কোনো অর্থ কাটা হয় না।',success:'আপনার প্রতিক্রিয়া সংরক্ষিত হয়েছে এবং হাসপাতাল দেখতে পাবে।',error:'লাইভ দানের তথ্য লোড করা যায়নি।',posted:'প্রকাশিত',target:'লক্ষ্য',needed:'প্রয়োজন',location:'স্থান উল্লেখ নেই'});
Object.assign(COPY.mr,{emptyText:'रुग्णालय प्रशासकाने प्रकाशित करताच विनंत्या येथे दिसतील.',contributed:'वचनबद्ध रक्कम',responses:'पाठवलेले प्रतिसाद',active:'रुग्णालयाच्या प्रतिसादाची प्रतीक्षा',matching:'सुसंगत रक्त विनंत्या',noMatch:'कोणतीही सुसंगत सक्रिय रक्त विनंती उपलब्ध नाही.',disclaimer:'हे फक्त वचन किंवा संपर्क विनंती नोंदवते. या वेबसाइटवर कोणतेही पैसे आकारले जात नाहीत.',success:'तुमचा प्रतिसाद जतन झाला असून रुग्णालयाला दिसेल.',error:'थेट देणगी डेटा लोड करता आला नाही.',posted:'प्रकाशित',target:'लक्ष्य',needed:'आवश्यक',location:'स्थान नमूद केलेले नाही'});
Object.assign(COPY.gu,{emptyText:'હોસ્પિટલ સંચાલક પ્રકાશિત કરશે ત્યારે વિનંતી અહીં દેખાશે.',contributed:'વચનબદ્ધ રકમ',responses:'મોકલેલા પ્રતિસાદ',active:'હોસ્પિટલના જવાબની રાહ',matching:'સુસંગત રક્ત વિનંતીઓ',noMatch:'કોઈ સુસંગત સક્રિય રક્ત વિનંતી નથી.',disclaimer:'આ ફક્ત વચન અથવા સંપર્ક વિનંતી નોંધે છે. આ વેબસાઇટ પર કોઈ ચુકવણી લેવામાં આવતી નથી.',success:'તમારો પ્રતિસાદ સાચવાયો છે અને હોસ્પિટલને દેખાશે.',error:'લાઇવ દાન ડેટા લોડ થઈ શક્યો નથી.',posted:'પ્રકાશિત',target:'લક્ષ્ય',needed:'જરૂરી',location:'સ્થાન આપેલ નથી'});
Object.assign(COPY.kn,{emptyText:'ಆಸ್ಪತ್ರೆಯ ನಿರ್ವಾಹಕರು ಪ್ರಕಟಿಸಿದ ತಕ್ಷಣ ವಿನಂತಿಗಳು ಇಲ್ಲಿ ಕಾಣಿಸುತ್ತವೆ.',contributed:'ವಾಗ್ದಾನ ಮಾಡಿದ ಮೊತ್ತ',responses:'ಕಳುಹಿಸಿದ ಪ್ರತಿಕ್ರಿಯೆಗಳು',active:'ಆಸ್ಪತ್ರೆಯ ಪ್ರತಿಕ್ರಿಯೆಗಾಗಿ',matching:'ಹೊಂದಾಣಿಕೆಯ ರಕ್ತ ವಿನಂತಿಗಳು',noMatch:'ಹೊಂದಾಣಿಕೆಯ ಸಕ್ರಿಯ ರಕ್ತ ವಿನಂತಿ ಇಲ್ಲ.',disclaimer:'ಇದು ವಾಗ್ದಾನ ಅಥವಾ ಸಂಪರ್ಕ ವಿನಂತಿಯನ್ನು ಮಾತ್ರ ದಾಖಲಿಸುತ್ತದೆ. ಈ ವೆಬ್‌ಸೈಟ್‌ನಲ್ಲಿ ಯಾವುದೇ ಪಾವತಿ ವಿಧಿಸಲಾಗುವುದಿಲ್ಲ.',success:'ನಿಮ್ಮ ಪ್ರತಿಕ್ರಿಯೆಯನ್ನು ಉಳಿಸಲಾಗಿದೆ ಮತ್ತು ಆಸ್ಪತ್ರೆಯು ನೋಡಬಹುದು.',error:'ಲೈವ್ ದೇಣಿಗೆ ಡೇಟಾವನ್ನು ಲೋಡ್ ಮಾಡಲಾಗಲಿಲ್ಲ.',posted:'ಪ್ರಕಟಿಸಲಾಗಿದೆ',target:'ಗುರಿ',needed:'ಅಗತ್ಯ',location:'ಸ್ಥಳವನ್ನು ಸೂಚಿಸಲಾಗಿಲ್ಲ'});
Object.assign(COPY.ml,{emptyText:'ആശുപത്രി അഡ്മിനിസ്ട്രേറ്റർ പ്രസിദ്ധീകരിച്ചാൽ അഭ്യർത്ഥനകൾ ഇവിടെ കാണും.',contributed:'വാഗ്ദാനം ചെയ്ത തുക',responses:'അയച്ച പ്രതികരണങ്ങൾ',active:'ആശുപത്രിയുടെ പ്രതികരണത്തിനായി',matching:'അനുയോജ്യമായ രക്ത അഭ്യർത്ഥനകൾ',noMatch:'അനുയോജ്യമായ സജീവ രക്ത അഭ്യർത്ഥന ലഭ്യമല്ല.',disclaimer:'ഇത് വാഗ്ദാനം അല്ലെങ്കിൽ ബന്ധപ്പെടാനുള്ള അഭ്യർത്ഥന മാത്രം രേഖപ്പെടുത്തുന്നു. ഈ വെബ്‌സൈറ്റിൽ പണം ഈടാക്കില്ല.',success:'നിങ്ങളുടെ പ്രതികരണം സംരക്ഷിച്ചു, ആശുപത്രിക്ക് കാണാം.',error:'ലൈവ് സംഭാവന ഡാറ്റ ലോഡ് ചെയ്യാനായില്ല.',posted:'പ്രസിദ്ധീകരിച്ചത്',target:'ലക്ഷ്യം',needed:'ആവശ്യം',location:'സ്ഥലം വ്യക്തമാക്കിയിട്ടില്ല'});
const CATEGORY_META = { blood: { icon: Droplet, color: '#dc2626', bg: '#fff1f2' }, financial: { icon: IndianRupee, color: '#047857', bg: '#ecfdf5' }, equipment: { icon: Package, color: '#0369a1', bg: '#eff6ff' }, medicine: { icon: Pill, color: '#7c3aed', bg: '#f5f3ff' }, other: { icon: HeartHandshake, color: '#b45309', bg: '#fffbeb' } };
const requestLocation = (request, tr) => request.location || [request.hospitals?.city, request.hospitals?.state].filter(Boolean).join(', ') || tr.location;
function relativeTime(value, language) { const seconds = Math.round((new Date(value).getTime() - Date.now()) / 1000); const formatter = new Intl.RelativeTimeFormat(language || 'en', { numeric: 'auto' }); if (Math.abs(seconds) < 3600) return formatter.format(Math.round(seconds / 60), 'minute'); if (Math.abs(seconds) < 86400) return formatter.format(Math.round(seconds / 3600), 'hour'); return formatter.format(Math.round(seconds / 86400), 'day'); }

export default function DonationsTab({ patientId }) {
  const { currentLang } = useLanguage();
  const tr = { ...COPY.en, ...(COPY[currentLang] || {}) };
  const [, setTranslationTick] = useState(0);
  useEffect(() => aiTranslationService.subscribe(() => setTranslationTick(value => value + 1)), []);
  const localize = (text, type = 'general') => currentLang === 'en' ? (text || '') : aiTranslationService.translate(text || '', currentLang, type);
  const [requests, setRequests] = useState([]), [contributions, setContributions] = useState([]);
  const [category, setCategory] = useState('all'), [query, setQuery] = useState(''), [bloodGroup, setBloodGroup] = useState('');
  const [selected, setSelected] = useState(null), [showHistory, setShowHistory] = useState(false);
  const [loading, setLoading] = useState(true), [error, setError] = useState(''), [success, setSuccess] = useState(''), [submitting, setSubmitting] = useState(false);
  const [form, setForm] = useState({ amount: '', units: '1', message: '' });
  const load = async () => { setLoading(true); setError(''); const [{ data: live, error: requestError }, { data: mine, error: contributionError }, patientResult] = await Promise.all([db.donations.getActiveRequests(), db.donations.getContributions(patientId), patientId ? db.patients.getById(patientId) : Promise.resolve({ data: null })]); setRequests(live || []); setContributions(mine || []); if (patientResult.data?.blood_group) setBloodGroup(patientResult.data.blood_group); if (requestError || contributionError) setError((requestError || contributionError).message || tr.error); setLoading(false); };
  useEffect(() => { load(); }, [patientId]); // eslint-disable-line react-hooks/exhaustive-deps
  const filtered = useMemo(() => requests.filter(request => { if (category !== 'all' && request.category !== category) return false; if (category === 'blood' && bloodGroup && !DONOR_COMPATIBILITY[bloodGroup]?.includes(request.blood_group)) return false; return `${request.title} ${request.description} ${request.hospitals?.name || ''} ${requestLocation(request, tr)}`.toLowerCase().includes(query.trim().toLowerCase()); }), [requests, category, query, bloodGroup, tr]);
  const moneyPledged = contributions.filter(item => item.contribution_type === 'funds' && item.status !== 'cancelled').reduce((sum, item) => sum + Number(item.amount_inr || 0), 0);
  const awaiting = contributions.filter(item => ['pledged', 'contact_requested', 'confirmed'].includes(item.status)).length;
  const chooseBloodGroup = async group => { setBloodGroup(group); setCategory('blood'); if (patientId) { const { error: saveError } = await db.patients.updateBloodGroup(patientId, group); if (saveError) setError(saveError.message); } };
  const openResponse = request => { setSelected(request); setSuccess(''); setError(''); setForm({ amount: '', units: '1', message: '' }); };
  const submitResponse = async event => { event.preventDefault(); if (!selected || !patientId) { setError('Please sign in as a patient before responding.'); return; } const responseType = selected.category === 'blood' ? 'blood_response' : selected.category === 'financial' ? 'funds' : selected.category; setSubmitting(true); setError(''); const { error: responseError } = await db.donations.respond({ requestId: selected.id, patientId, contributionType: responseType, amountInr: selected.category === 'financial' ? form.amount : null, unitsOffered: selected.category === 'blood' ? form.units : null, bloodGroup: selected.category === 'blood' ? bloodGroup : null, message: form.message }); setSubmitting(false); if (responseError) { setError(responseError.code === '23505' ? 'You have already responded to this request.' : responseError.message); return; } setSuccess(tr.success); await load(); };
  return <section className="donations-page" aria-label={tr.title}>
    <div className="donations-heading"><div><span className="donations-kicker">Patient Portal / {tr.title}</span><h1>{tr.title}</h1><p>{tr.subtitle}</p></div><button className="donation-history-btn" onClick={() => setShowHistory(true)}><Clock3 size={17}/>{tr.history}</button></div>
    <div className="donations-hero"><div><h2>{tr.hero} <span>♥</span></h2><p>{tr.heroText}</p></div><div className="donations-hero-art"><HeartHandshake size={64}/></div></div>
    <div className="donations-summary"><div><IndianRupee size={21}/><span><strong>{moneyPledged.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0})}</strong>{tr.contributed}</span></div><div><HeartHandshake size={21}/><span><strong>{contributions.length}</strong>{tr.responses}</span></div><div><Clock3 size={21}/><span><strong>{awaiting}</strong>{tr.active}</span></div></div>
    <div className="donation-toolbar"><div className="donation-tabs" role="tablist">{['all','blood','financial','equipment','medicine','other'].map(item => <button key={item} role="tab" aria-selected={category === item} className={category === item ? 'active' : ''} onClick={() => setCategory(item)}>{tr[item]}</button>)}</div><label className="donation-search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder={tr.search} aria-label={tr.search}/></label></div>
    {category === 'blood' && <div className="blood-selector"><div><Droplet size={26}/><span><strong>{tr.selectBlood}</strong><small>{bloodGroup ? `${tr.matching}: ${bloodGroup}` : tr.matching}</small></span></div><div className="blood-groups">{GROUPS.map(group => <button key={group} className={bloodGroup === group ? 'selected' : ''} onClick={() => chooseBloodGroup(group)}>{group}</button>)}</div></div>}
    {error && !selected && <div className="donation-alert error"><AlertCircle size={19}/><span>{tr.error} {error}</span><button onClick={load}>{tr.retry}</button></div>}
    {loading ? <div className="donation-state"><RefreshCw className="spin" size={34}/><h3>{tr.loading}</h3></div> : filtered.length === 0 ? <div className="donation-state"><HeartHandshake size={45}/><h3>{category === 'blood' && bloodGroup ? tr.noMatch : tr.empty}</h3><p>{tr.emptyText}</p><button onClick={load}><RefreshCw size={16}/>{tr.retry}</button></div> : <div className="donation-request-grid">{filtered.map(request => { const meta = CATEGORY_META[request.category] || CATEGORY_META.other, Icon = meta.icon; return <article className="donation-request-card" key={request.id}><div className="request-card-top"><span className="request-icon" style={{color:meta.color,background:meta.bg}}><Icon size={24}/></span><span className={`urgency urgency-${request.urgency}`}>{localize(request.urgency)}</span></div><h3>{localize(request.title)}</h3><p className="request-hospital">{localize(request.hospitals?.name,'name') || tr.hospital}</p><p className="request-description">{localize(request.description)}</p>{request.patient_summary && <p className="patient-summary"><ShieldCheck size={15}/>{localize(request.patient_summary)}</p>}<div className="request-facts"><span><MapPin size={15}/>{localize(requestLocation(request,tr))}</span><span><Clock3 size={15}/>{tr.posted} {relativeTime(request.created_at,currentLang)}</span></div>{request.category === 'blood' && <div className="request-need"><strong>{request.blood_group}</strong><span>{request.units_needed-request.units_fulfilled} {tr.needed}</span></div>}{request.category === 'financial' && <div className="request-progress"><div><span>{tr.target}</span><strong>{Number(request.amount_target).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0})}</strong></div><progress max={request.amount_target} value={Math.min(request.amount_received,request.amount_target)}/></div>}<button className="request-action" onClick={() => openResponse(request)} disabled={request.category === 'blood' && !bloodGroup}>{request.category === 'blood' && !bloodGroup ? tr.selectBlood : tr.view}</button></article>; })}</div>}
    {selected && <div className="donation-modal-backdrop" onMouseDown={e => {if(e.target===e.currentTarget)setSelected(null)}}><div className="donation-modal" role="dialog" aria-modal="true"><button className="modal-close" onClick={() => setSelected(null)} aria-label={tr.close}><X/></button><span className="modal-hospital">{selected.hospitals?.name}</span><h2>{selected.title}</h2><p>{selected.description}</p>{success ? <div className="response-success"><CheckCircle2 size={32}/><strong>{success}</strong><button onClick={() => setSelected(null)}>{tr.close}</button></div> : <form onSubmit={submitResponse}>{selected.category === 'financial' && <label>{tr.amount}<input required min="1" step="1" type="number" value={form.amount} onChange={e => setForm({...form,amount:e.target.value})}/></label>}{selected.category === 'blood' && <><div className="selected-blood">{tr.selectBlood}: <strong>{bloodGroup}</strong></div><label>{tr.units}<input required min="1" max="20" type="number" value={form.units} onChange={e => setForm({...form,units:e.target.value})}/></label></>}<label>{tr.message}<textarea maxLength="1000" rows="4" value={form.message} onChange={e => setForm({...form,message:e.target.value})}/></label><div className="pledge-notice"><ShieldCheck size={18}/>{tr.disclaimer}</div>{error && <div className="inline-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={() => setSelected(null)}>{tr.cancel}</button><button type="submit" disabled={submitting}>{submitting ? tr.loading : tr.submit}</button></div></form>}</div></div>}
    {showHistory && <div className="donation-modal-backdrop" onMouseDown={e => {if(e.target===e.currentTarget)setShowHistory(false)}}><div className="donation-modal history-modal"><button className="modal-close" onClick={() => setShowHistory(false)} aria-label={tr.close}><X/></button><h2>{tr.history}</h2>{contributions.length === 0 ? <div className="history-empty">{tr.empty}</div> : <div className="history-list">{contributions.map(item => <div key={item.id}><span className="history-icon"><HeartHandshake size={18}/></span><div><strong>{item.donation_requests?.title || tr.responses}</strong><small>{item.donation_requests?.hospitals?.name} · {new Date(item.created_at).toLocaleDateString(currentLang)}</small></div><span className="history-value">{item.amount_inr ? Number(item.amount_inr).toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}) : item.units_offered ? `${item.units_offered} unit` : item.status}</span></div>)}</div>}</div></div>}
  </section>;
}
